In [71]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [72]:
#reading dataset with datetime
losdata = pd.read_csv("losangeles.csv",parse_dates=True)  
losdata = losdata.dropna() #drops NaN values
losdata = losdata.sample(n=10000, replace=True) #choosing 10000 random instance
losdata = losdata.loc[:,["AREA.NAME","CrmCd.Desc","DATE.OCC","TIME.OCC"]] #subset important columns
print(losdata.info)

<bound method DataFrame.info of           AREA.NAME                                         CrmCd.Desc  \
610737      West LA                                       TRAFFIC DR #   
622545      Pacific                                       TRAFFIC DR #   
149923    Hollywood                                  ATTEMPTED ROBBERY   
430518  77th Street                                       TRAFFIC DR #   
863526      Pacific  VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...   
...             ...                                                ...   
412694      Central                                       TRAFFIC DR #   
901192      Pacific                              BURGLARY FROM VEHICLE   
909037      Rampart                                       TRAFFIC DR #   
279476    Southeast                                          PANDERING   
201944      Mission                                       TRAFFIC DR #   

          DATE.OCC  TIME.OCC  
610737  03/14/2014      2130  
622545  09/01/201

In [73]:
#reading dataset for denver dataset
denverdata = pd.read_csv("crime.csv", parse_dates=True)
denverdata = denverdata.dropna() #drops NaN values
denverdata = denverdata.sample(n=10000, replace=True) #choosing 10000 random instance
denverdata = denverdata.loc[:,["OFFENSE_CATEGORY_ID","FIRST_OCCURRENCE_DATE","NEIGHBORHOOD_ID","IS_CRIME"]] #subset important columns
denverdata = denverdata[denverdata["IS_CRIME"]==1]
print(denverdata.head())

             OFFENSE_CATEGORY_ID  FIRST_OCCURRENCE_DATE NEIGHBORHOOD_ID  \
415171  theft-from-motor-vehicle   7/26/2019 4:30:00 PM         hampden   
156469           public-disorder   3/29/2016 6:45:00 AM    country-club   
402245                auto-theft  12/28/2015 3:30:00 PM         kennedy   
373396  theft-from-motor-vehicle  10/23/2016 8:00:00 PM       stapleton   
350867                auto-theft  12/29/2015 8:30:00 PM        westwood   

        IS_CRIME  
415171         1  
156469         1  
402245         1  
373396         1  
350867         1  


In [74]:
#FOR CRIME_DAY AND CRIME_MONTH in losdataset
losdata["Crime_Day"] = losdata["DATE.OCC"].str.split('/').str[1]
losdata["Crime_Month"] = losdata["DATE.OCC"].str.split('/').str[0]
print(losdata.head())

          AREA.NAME                                         CrmCd.Desc  \
610737      West LA                                       TRAFFIC DR #   
622545      Pacific                                       TRAFFIC DR #   
149923    Hollywood                                  ATTEMPTED ROBBERY   
430518  77th Street                                       TRAFFIC DR #   
863526      Pacific  VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...   

          DATE.OCC  TIME.OCC Crime_Day Crime_Month  
610737  03/14/2014      2130        14          03  
622545  09/01/2014      2230        01          09  
149923  05/16/2012      1410        16          05  
430518  07/06/2013      2000        06          07  
863526  04/16/2015       816        16          04  


In [75]:
#FOR CRIME_DAY AND CRIME_MONTH in denverdataset
del denverdata["IS_CRIME"]
denverdata['FIRST_OCCURRENCE_DATE'] =  pd.to_datetime(denverdata['FIRST_OCCURRENCE_DATE'])
denverdata["Crime_Day"] = denverdata["FIRST_OCCURRENCE_DATE"].dt.date.astype(str).str.split('-').str[2]
denverdata["Crime_Month"] = denverdata["FIRST_OCCURRENCE_DATE"].dt.date.astype(str).str.split('-').str[1]
print(denverdata.head())

             OFFENSE_CATEGORY_ID FIRST_OCCURRENCE_DATE NEIGHBORHOOD_ID  \
415171  theft-from-motor-vehicle   2019-07-26 16:30:00         hampden   
156469           public-disorder   2016-03-29 06:45:00    country-club   
402245                auto-theft   2015-12-28 15:30:00         kennedy   
373396  theft-from-motor-vehicle   2016-10-23 20:00:00       stapleton   
350867                auto-theft   2015-12-29 20:30:00        westwood   

       Crime_Day Crime_Month  
415171        26          07  
156469        29          03  
402245        28          12  
373396        23          10  
350867        29          12  


In [76]:
del losdata["DATE.OCC"]
#renaming columns in losdataset to match the format 
losdata = losdata.rename(columns={"AREA.NAME":"Crime_Location", "CrmCd.Desc":"Crime_Type"})
print(losdata.head())

       Crime_Location                                         Crime_Type  \
610737        West LA                                       TRAFFIC DR #   
622545        Pacific                                       TRAFFIC DR #   
149923      Hollywood                                  ATTEMPTED ROBBERY   
430518    77th Street                                       TRAFFIC DR #   
863526        Pacific  VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...   

        TIME.OCC Crime_Day Crime_Month  
610737      2130        14          03  
622545      2230        01          09  
149923      1410        16          05  
430518      2000        06          07  
863526       816        16          04  


In [77]:
#renaming the columns in denverdataset to match the format
denverdata = denverdata.rename(columns={"OFFENSE_CATEGORY_ID":"Crime_Type","NEIGHBORHOOD_ID":"Crime_Location"})
print(denverdata.head())

                      Crime_Type FIRST_OCCURRENCE_DATE Crime_Location  \
415171  theft-from-motor-vehicle   2019-07-26 16:30:00        hampden   
156469           public-disorder   2016-03-29 06:45:00   country-club   
402245                auto-theft   2015-12-28 15:30:00        kennedy   
373396  theft-from-motor-vehicle   2016-10-23 20:00:00      stapleton   
350867                auto-theft   2015-12-29 20:30:00       westwood   

       Crime_Day Crime_Month  
415171        26          07  
156469        29          03  
402245        28          12  
373396        23          10  
350867        29          12  


In [78]:
#FOR CRIME_TIME in los dataset
h = lambda x: "T1" if(x>=100 and x<500) else("T2" 
                if(x>=500 and x<900) else("T3" 
                if(x>=900 and x<1300) else("T4" 
                if(x>=1300 and x<1700) else("T5" 
                if(x>=1700 and x<2100) else "T6"))))

losdata['Crime_Time'] = list(map(h,losdata['TIME.OCC']))

del losdata['TIME.OCC']
print(losdata.head())

       Crime_Location                                         Crime_Type  \
610737        West LA                                       TRAFFIC DR #   
622545        Pacific                                       TRAFFIC DR #   
149923      Hollywood                                  ATTEMPTED ROBBERY   
430518    77th Street                                       TRAFFIC DR #   
863526        Pacific  VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...   

       Crime_Day Crime_Month Crime_Time  
610737        14          03         T6  
622545        01          09         T6  
149923        16          05         T4  
430518        06          07         T5  
863526        16          04         T2  


In [60]:
# denverdata["Crime_Time"] = denverdata["FIRST_OCCURRENCE_DATE"].dt.hour
# print(denverdata['Crime_Time'].dtype)
# print(denverdata['Crime_Time'].describe)
# print(np.unique(denverdata['Crime_Time']))
# i = lambda x: "T1" if(x>=1 and x<5) else("T2" 
#                 if(x>=5 and x<9) else("T3" 
#                 if(x>=9 and x<13) else("T4" 
#                 if(x>=13 and x<17) else("T5" 
#                 if(x>=17 and x<21) else "T6"))))

# print(np.unique(list(map(i,denverdata['Crime_Time']))))

int64
<bound method NDFrame.describe of 253481    17
52336      0
362197    16
307835    21
6963      18
          ..
323129    17
203436     0
500145    20
474742    21
72312     11
Name: Crime_Time, Length: 9974, dtype: int64>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
['T1' 'T2' 'T3' 'T4' 'T5' 'T6']


In [79]:
#FOR CRIME_TIME in denverdataset
denverdata["Crime_Time"] = denverdata["FIRST_OCCURRENCE_DATE"].dt.hour

i = lambda x: "T1" if(x>=1 and x<5) else("T2" 
                if(x>=5 and x<9) else("T3" 
                if(x>=9 and x<13) else("T4" 
                if(x>=13 and x<17) else("T5" 
                if(x>=17 and x<21) else "T6"))))

denverdata['Crime_Time'] = list(map(i,denverdata['Crime_Time']))

del denverdata["FIRST_OCCURRENCE_DATE"]
print(denverdata.head())

                      Crime_Type Crime_Location Crime_Day Crime_Month  \
415171  theft-from-motor-vehicle        hampden        26          07   
156469           public-disorder   country-club        29          03   
402245                auto-theft        kennedy        28          12   
373396  theft-from-motor-vehicle      stapleton        23          10   
350867                auto-theft       westwood        29          12   

       Crime_Time  
415171         T4  
156469         T2  
402245         T4  
373396         T5  
350867         T5  


In [80]:
print(denverdata['Crime_Time'].describe)

<bound method NDFrame.describe of 415171    T4
156469    T2
402245    T4
373396    T5
350867    T5
          ..
175414    T2
351338    T2
284742    T4
289452    T3
185715    T2
Name: Crime_Time, Length: 9982, dtype: object>


In [81]:
#FOR CRIME_TYPE in losdataset
j = lambda x: "THEFT" if(x.find("BURGALORY")>0 or x.find("ROBBERY")>0 or x.find("THEFT")>0 or 
               x.find("STOLEN")>0 or x.find("SNATCHING")>0 or x.find("STEALING")>0 or 
               x.find("FELONY")>0 or x.find("PICKPOCKET")>0 or x.find("BUNCO")>0 or
               x.find("EMBEZZLEMENT")>0) else ("ASSAULT" 
            if (x.find("ASSAULT")>0 or x.find("BATTERY")>0 or x.find("VANDALISM")>0 or 
                 x.find("SCARE")>0 or x.find("THREATS")>0 or x.find("ABUSE")>0 or x.find("SHOTS")>0 or 
                 x.find("SEXUAL")>0 or x.find("THROWING")>0 or x.find("COPULATION")>0 or 
                 x.find("EXTORTION")>0 or x.find("STALKING")>0 or x.find("KIDNAPPING")>0 or 
                 x.find("ENDANGERMENT")>0 or x.find("ANNOYING")>0 or x.find("HOMICIDE")>0 )else ("DRUG ALCOHOL" 
    if (x.find("DR")>0 or x.find("BRANDISH")>0 or x.find("WEAPON")>0 or x.find("LEAD")>0) else("PUBLIC DISORDER" 
    if (x.find("DISTURBING")>0 or x.find("ARSON")>0) else("OTHER CRIMES" 
    if (x.find("TRESPASSING")>0 or x.find("CRUELTY")>0 or x.find("WITHOUT")>0) else "WHITE COLLAR CRIMES"))))

losdata["Crime_Type"] = list(map(j,losdata["Crime_Type"]))

g = lambda x: 5 if x=="THEFT" else( 1
            if x=="ASSAULT" else( 2
            if x=="DRUG ALCOHOL" else (4
            if x=="PUBLIC DISORDER" else( 3
            if x=="OTHER CRIMES" else 6 ))))

losdata['Crime_Type_Id'] = list(map(g,losdata['Crime_Type']))

print(losdata.head())

       Crime_Location    Crime_Type Crime_Day Crime_Month Crime_Time  \
610737        West LA  DRUG ALCOHOL        14          03         T6   
622545        Pacific  DRUG ALCOHOL        01          09         T6   
149923      Hollywood         THEFT        16          05         T4   
430518    77th Street  DRUG ALCOHOL        06          07         T5   
863526        Pacific         THEFT        16          04         T2   

        Crime_Type_Id  
610737              2  
622545              2  
149923              5  
430518              2  
863526              5  


In [82]:
#FOR CRIME_TYPE in denver dataset
f = lambda x: "ASSAULT" if(x.find("assault")>0 or x.find("sexual")>0) else ("DRUG ALCOHOL" 
            if(x.find("drug")>0 or x.find("alcohol")>0) else ( "OTHER CRIMES" 
            if(x.find("other-crimes")>0) else ( "PUBLIC DISORDER" 
            if(x.find("public")>0 or x.find("disorder")>0) else ( "WHITE COLLAR CRIMES" 
            if(x.find("white")>0 or x.find("collar-crime")>0) else "THEFT"))))
denverdata["Crime_Type"] = list(map(f,denverdata['Crime_Type']))

denverdata['Crime_Type_Id'] = list(map(g,denverdata['Crime_Type']))

print(denverdata.head())

             Crime_Type Crime_Location Crime_Day Crime_Month Crime_Time  \
415171            THEFT        hampden        26          07         T4   
156469  PUBLIC DISORDER   country-club        29          03         T2   
402245            THEFT        kennedy        28          12         T4   
373396            THEFT      stapleton        23          10         T5   
350867            THEFT       westwood        29          12         T5   

        Crime_Type_Id  
415171              5  
156469              4  
402245              5  
373396              5  
350867              5  


In [92]:
#Splitting Data into testing and training 
from sklearn import preprocessing

#Losdatset splitting
le = preprocessing.LabelEncoder()
df = pd.DataFrame(np.random.randn(len(losdata), 2)) 
msk = np.random.rand(len(df)) < 0.8

train = losdata[msk]
test = losdata[~msk]

for column_name in train.columns:
        if train[column_name].dtype == object:
            train[column_name] = le.fit_transform(train[column_name])

for column_name in test.columns:
        if test[column_name].dtype == object:
            test[column_name] = le.fit_transform(test[column_name])

#DenverDataset Splitting
le2 = preprocessing.LabelEncoder()
df2 = pd.DataFrame(np.random.randn(len(denverdata), 2))
msk2  = np.random.rand(len(df2)) < 0.8

train2 = denverdata[msk2]
test2 = denverdata[~msk2]

for column_name in train2.columns:
        if train2[column_name].dtype == object:
            train2[column_name] = le2.fit_transform(train2[column_name])

for column_name in test2.columns:
        if test2[column_name].dtype == object:
            test2[column_name] = le2.fit_transform(test2[column_name])

/home/srix/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/home/srix/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/srix/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pand

In [93]:
#Naive Bayes for LosAngeles Dataset
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

print('========LOS ANGELES==============')
naiveclf = GaussianNB()
naiveclf.fit(train.loc[:,['Crime_Location','Crime_Day','Crime_Month','Crime_Time']],
             train.loc[:,"Crime_Type_Id"])
target_pred = naiveclf.predict(test.loc[:,['Crime_Location', 'Crime_Day', 'Crime_Month','Crime_Time']])
print("Accuracy -",accuracy_score(test.loc[:,"Crime_Type_Id"], target_pred, normalize=True))
print(confusion_matrix(test.loc[:,["Crime_Type_Id"]], target_pred))
print('----------------------------------')

========LOS ANGELES==============
Accuracy - 0.5503560528992879
[[   0  217    0    0    0]
 [   0 1082    0    0    0]
 [   0    5    0    0    0]
 [   0  177    0    0    0]
 [   0  485    0    0    0]]
----------------------------------


In [94]:
#Naive Bayes for Denver Dataset
print('========DENVER====================')
naiveclf2 = GaussianNB()
naiveclf2.fit(train2.loc[:,['Crime_Location', 'Crime_Day', 'Crime_Month','Crime_Time']],
              train2.loc[:,"Crime_Type_Id"])
target_pred2 = naiveclf2.predict(test2.loc[:,['Crime_Location', 'Crime_Day', 'Crime_Month','Crime_Time']])
print("Accuracy -",accuracy_score(test2.loc[:,"Crime_Type_Id"], target_pred2, normalize=True))
print(confusion_matrix(test2.loc[:,"Crime_Type_Id"], target_pred2))
print('----------------------------------')

========DENVER====================
Accuracy - 0.7669322709163346
[[   0    0    0    0   48    0]
 [   0    0    0    0    9    0]
 [   0    0    0    0   62    0]
 [   0    0    0    0  301    0]
 [   0    0    0    0 1540    0]
 [   0    0    0    0   48    0]]
----------------------------------


In [95]:
#Decision Tree for LosAngeles Dataset
from sklearn import tree
# from sklearn.externals.six import StringIO  
# from IPython.display import Image  
# from sklearn.tree import export_graphviz
# import graphviz
# import pydotplus

print('========LOS ANGELES==============')
model = tree.DecisionTreeClassifier() 
model.fit(train.iloc[:,[0,2,3,4]],train.iloc[:,5])
decision_pred = model.predict(test.iloc[:,[0,2,3,4]])
print("Accuracy -",accuracy_score(test.iloc[:,5], decision_pred, normalize=True))
print(confusion_matrix(test.iloc[:,5], decision_pred))
print('=================================')
# plotting decision tree, usually takes a lot of time. Uncomment other lines to plot

# dot_data = StringIO()
# export_graphviz(model, out_file=dot_data, 
#                 feature_names=['Crime_Location', 'Crime_Day', 'Crime_Month','Crime_Time'], 
#                 class_names=["1","2","3","4","5","6"],
#                 filled=True, rounded=True,
#                 special_characters=True)
# graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
# Image(graph.create_png())

========LOS ANGELES==============
Accuracy - 0.4150559511698881
[[ 33 117   0  19  48]
 [108 645   0  87 242]
 [  0   4   0   0   1]
 [ 23  84   0  28  42]
 [ 54 272   0  49 110]]


In [96]:
#decision tree for denver dataset
print('========DENVER====================')
model2 = tree.DecisionTreeClassifier() 
model2.fit(train2.iloc[:,[1,2,3,4]],train2.iloc[:,5])
decision_pred2 = model2.predict(test2.iloc[:,[1,2,3,4]])
print("Accuracy -",accuracy_score(test2.iloc[:,5], decision_pred2, normalize=True))
print(confusion_matrix(test2.iloc[:,5], decision_pred2))
print('==================================')
# dot_data2 = StringIO()
# export_graphviz(model2, out_file=dot_data2, 
#                 feature_names=['Crime_Location', 'Crime_Day', 'Crime_Month','Crime_Time'], 
#                 class_names=["1","2","3","4","5","6"],
#                 filled=True, rounded=True,
#                 special_characters=True)
# graph2 = pydotplus.graph_from_dot_data(dot_data2.getvalue())  
# Image(graph2.create_png())

========DENVER====================
Accuracy - 0.5981075697211156
[[   5    0    3    6   34    0]
 [   0    0    0    4    5    0]
 [   3    0   10   10   38    1]
 [   6    1    7   66  207   14]
 [  31   10   61  274 1115   49]
 [   0    0    3    3   37    5]]


In [97]:
#RandomForest for LosAngeles Dataset
from sklearn.ensemble import RandomForestClassifier
clf4 = RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0)
clf4.fit(train.iloc[:,[0,2,3,4]],train.iloc[:,5])
print(clf4.feature_importances_)
losforest_pred = clf4.predict(test.iloc[:,[0,2,3,4]])
print('========LOS ANGELES==============')
print("Accuracy -",accuracy_score(test.iloc[:,5], losforest_pred, normalize=True))
print(confusion_matrix(test.iloc[:,5], losforest_pred))
print('=================================')

[0.50550579 0.06076133 0.02367404 0.41005884]
========LOS ANGELES==============
Accuracy - 0.5503560528992879
[[   0  217    0    0    0]
 [   0 1082    0    0    0]
 [   0    5    0    0    0]
 [   0  177    0    0    0]
 [   0  485    0    0    0]]


In [98]:
#Random Forest for Denver Dataset
clf3 = RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0)
clf3.fit(train2.iloc[:,[1,2,3,4]],train2.iloc[:,5])
print(clf3.feature_importances_)       #finding importance of features
denverforest_pred = clf3.predict(test2.iloc[:,[1,2,3,4]])
print('========DENVER====================')
print("Accuracy -",accuracy_score(test2.iloc[:,5], denverforest_pred, normalize=True))
print(confusion_matrix(test2.iloc[:,5], decision_pred2))
print('==================================')

[0.27681441 0.1127179  0.33224711 0.27822057]
========DENVER====================
Accuracy - 0.7669322709163346
[[   5    0    3    6   34    0]
 [   0    0    0    4    5    0]
 [   3    0   10   10   38    1]
 [   6    1    7   66  207   14]
 [  31   10   61  274 1115   49]
 [   0    0    3    3   37    5]]


In [17]:
# #apriori algorithm 
# from apyori import apriori
# records = []
# for i in range(0, len(losdata)):
#     records.append([str(losdata.values[i,j]) for j in range(0, 6)])
# association_rules = apriori(records, min_support=0.0018, min_confidence=0.50, min_lift=3, min_length=2)
# association_results = list(association_rules)
# print(len(association_results))
# for item in association_results:
#     # first index of the inner list
#     # Contains base item and add item
#     pair = item[0]
#     items = [x for x in pair]
#     print("Rule: " + str(list(item.ordered_statistics[0].items_base)) + " -> " + str(list(item.ordered_statistics[0].items_add)))
#     #second index of the inner list
#     print("Support: " + str(item[1]))
#     #third index of the list located at 0th
#     #of the third index of the inner list
#     print("Confidence: " + str(item[2][0][2]))
#     print("=====================================")

In [18]:
# records2 = []
# for i in range(0, len(denverdata)):
#     records2.append([str(denverdata.values[i,j]) for j in range(0, 6)])
# association_rules2 = apriori(records2, min_support=0.0018, min_confidence=0.50, min_lift=3, min_length=2)
# association_results2 = list(association_rules2)
# print(len(association_results2))
# for item2 in association_results2:
#     # first index of the inner list
#     # Contains base item and add item
#     pair2 = item2[0]
#     items2 = [x for x in pair2]
#     print("Rule: " + str(list(item2.ordered_statistics[0].items_base)) + " -> " + str(list(item2.ordered_statistics[0].items_add)))
#     #second index of the inner list
#     print("Support: " + str(item2[1]))
#     #third index of the list located at 0th
#     #of the third index of the inner list
#     print("Confidence: " + str(item2[2][0][2]))
#     print("=====================================")